# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5da01d42e1e2be6a7c4df4b9560058fb488a645c99620774923d54c7a465e26a696f308b80b2cbb104cba134ad4f1cacc0c4d21563115651bdb10396dadeb5bb

test:
  secret_key_base: 44b65c8aa376803aa571a7a42ade92f628c556993c85971a0eb51bd0f813945a82818ebe3d6c5bbf4757dad75d12df5c4af12d1f3fce903d810cb7a4f32d6de5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
